args <- commandArgs(trailingOnly = TRUE)
root <- normalizePath(if (length(args)) args[[1]] else ".")
fixtures <- file.path(root, "tests", "fixtures")
output <- tempfile("smart-tables-test-")
dir.create(output)

render <- function(name) {
  source <- file.path(fixtures, name)
  status <- system2("quarto", c("render", source, "--output-dir", output))
  if (status != 0) stop("Quarto render failed for ", name)
  path <- file.path(output, sub("\\.qmd$", ".html", name))
  if (!file.exists(path)) stop("Expected output not found: ", path)
  paste(readLines(path, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
}

expect <- function(html, pattern, label) {
  if (!grepl(pattern, html, perl = TRUE)) stop("Missing assertion: ", label)
}

html <- render("html-tables.qmd")
expect(html, "smart-table-wrap", "smart table wrapper")
expect(html, "smart-table-scroll", "outer scroll container")
expect(html, "smart-table-layout-planned", "planned HTML column widths")
expect(html, "width:[0-9.]+em !important", "intrinsic table width overrides theme CSS")
expect(html, "id=\"tbl-markdown\"", "captioned table identifier")
expect(html, "Caption preserved", "table caption")
expect(html, "Amount<br", "table option on a captioned table")
expect(html, "smart-table-header-lines", "calculated header lines are protected from CSS rewrapping")
expect(html, "https://quarto.org", "rich header link")
expect(html, "colspan=\"2\"", "colspan")
expect(html, "rowspan=\"2\"", "rowspan")
expect(html, "data-smart-tables-processed=\"true\"", "idempotence marker")
expect(html, "Table generated by knitr", "knitr caption")
raw <- sub("(?s).*?<div id=\"raw-html\">", "", html, perl = TRUE)
raw <- sub("(?s)</div>.*", "", raw, perl = TRUE)
if (!grepl("data-smart-tables-raw=\"true\"", raw, fixed = TRUE)) stop("Raw HTML marker was lost")
if (grepl("smart-table", raw, fixed = TRUE)) stop("Raw HTML kable output was transformed")

reveal <- render("revealjs-tables.qmd")
expect(reveal, "smart-table-reveal", "RevealJS wrapper")
expect(reveal, "smart-table-profile-reveal", "automatic RevealJS profile")
expect(reveal, "--smart-table-reveal-max-height:60vh", "RevealJS max height")
expect(reveal, "https://example.com", "RevealJS rich cell content")

stretch <- render("revealjs-auto-stretch.qmd")
expect(stretch, "smart-table-reveal", "auto-stretch RevealJS wrapper")
expect(stretch, "--smart-table-reveal-max-height:65vh", "auto-stretch height cap")

message("smart-typst-tables rendering checks passed")
